"""Add users table

Revision ID: fe56d98c20b0
Revises: 23a935f72b4a
Create Date: 2026-01-29 14:48:16.120650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe56d98c20b0'
down_revision: Union[str, Sequence[str], None] = '23a935f72b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('job_applications', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.alter_column('job_applications', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('job_applications', 'date_applied',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_foreign_key(None, 'job_applications', 'users', ['owner_id'], ['id'])
    op.drop_column('job_applications', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('notes', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'job_applications', type_='foreignkey')
    op.alter_column('job_applications', 'date_applied',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('job_applications', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('job_applications', 'owner_id')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
